60 new api for placeholder verifier
NilFoundation/mina-state-proof pull request #69
Opened 2023-04-19 11:26 UTC by ETatuzova

2023-04-20 10:04 UTC, hgedia requested changes
Reviewed only flow.

2023-04-20 10:52 UTC, ETatuzova commented on contracts/interfaces/IMinaPlaceholderVerifier.sol
> +        address verifier_address,
Yeah. These three addresses are similar for all mina-proofs. So they can be passed to this contract only once.

2023-04-20 22:29 UTC, nemothenoone approved these changes

2023-04-23 22:24 UTC, nemothenoone commented on contracts/interfaces/IMinaPlaceholderVerifier.sol
> +        address verifier_address,
Fixed by refactoring the function signature.

2023-04-23 22:25 UTC, nemothenoone approved these changes

2023-05-03 21:19 UTC, merged